### ISSUE TITLE
`svm install <version>` and `svm list` failures

### ISSUE THREAD

**Issue by mratsim** [alloy-rs/svm-rs#106]
The following functions from the README fail:

> -   List available versions
> 
> ```sh
> svm list
> ```
> 
> -   Install a version
> 
> ```sh
> svm install <version>
> ```

![image](https://github.com/alloy-rs/svm-rs/assets/22738317/1f36ba37-6ee8-46ad-8fe7-9fb506797c33)

Installation was from source via `cargo install --locked --git https://github.com/roynalnaruto/svm-rs`

**Comment by mattsse** [comment]
@mratsim sorry about the latest refactor introduced some issues -.-
