### ISSUE TITLE
svm-rs 0.5.4 -> 0.5.5 version bump may cause unexpected build failure

### ISSUE THREAD

**Issue by target-san** [alloy-rs/svm-rs#139]
This version bumps MSRV 1.70 -> 1.80.
If one has Rust version in his project pinned, this will cause unexpected build failure out of thin air.
I may be mistaken, yet AFAIR such changes should cause version bump 0.5.4 -> 0.6.0

**Comment by DaniPopes** [comment]
MSRV isn't covered by semver, nor does this project have any guarantees about it

**Comment by target-san** [comment]
We had Rust 1.79 pinned in our project. Problem is, `svm-rs` updated on CI to 0.5.5 at some point and we got CI failure out of thin air because `cargo install svm-rs@0.5` now installs `0.5.5`.
