### ISSUE TITLE
svm-rs cannot be built offline

### ISSUE THREAD

**Issue by farcaller** [alloy-rs/svm-rs#79]
svm-rs cannot be built offline because the `build.rs` requires internet connection to fetch the json with the versions. It makes it impossible to e.g. package anything that depends on svm-rs in nix, as the builder won't allow the outgoing http connections.

Please provide an alternative mechanism for allowing to pass the list offline. Currently, there's the `_offline` feature, but it will just result in an empty list. I suggest there's an environment variable that points to a pre-downloaded list (that's potentially checked into the version control elsewhere), and svm-builds should use it first (if the variable is set), falling back to fetching it online otherwise.

**Comment by mattsse** [comment]
agree this would be ideal
We just haven't gotten around to add this. I guess an easy solution would be to write a test that generates all files and the build script uses that as fallback

Do you want to take this on?
