### ISSUE TITLE
Why does my svm get installed to ~/.cargo/bin/svm instead of ./svm?

### ISSUE THREAD

**Issue by rahul0eth** [alloy-rs/svm-rs#99]
rahulbajaj@RB-MBP ~ % which svm                             
/Users/rahulbajaj/.cargo/bin/svm
rahulbajaj@RB-MBP ~ % ~/.svm/0.8.21/solc-0.8.21 --version
zsh: no such file or directory: /Users/rahulbajaj/.svm/0.8.21/solc-0.8.21
rahulbajaj@RB-MBP ~ % ~/.cargo/svm/0.8.21/solc-0.8.21 --version 
zsh: no such file or directory: /Users/rahulbajaj/.cargo/svm/0.8.21/solc-0.8.21
rahulbajaj@RB-MBP ~ % ~/.svm/0.8.21/solc-0.8.21 --version      
zsh: no such file or directory: /Users/rahulbajaj/.svm/0.8.21/solc-0.8.21

**Comment by mattsse** [comment]
this is how cargo installs, you can set a target path though
